[tool.isort]
force_single_line = true
force_alphabetical_sort_within_sections = true
lines_after_imports = 2

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--cov=app"
testpaths = ["tests"]
filterwarnings = [
    "ignore:^SelectableGroups dict interface is deprecated\\..*$:DeprecationWarning"
]
