name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install CI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl shellcheck
          sudo curl \
            -L https://raw.githubusercontent.com/nickjj/wait-until/v0.2.0/wait-until \
            -o /usr/local/bin/wait-until && sudo chmod +x /usr/local/bin/wait-until
      - name: Setup Docker
        run: |
          mv .env.example .env
          docker compose build
          docker compose up -d
          wait-until "docker compose exec -T postgres psql -U postgres postgres -c 'SELECT 1'"
          docker compose exec web alembic upgrade head
          docker compose exec web python -m app seed-db
        env:
          DOCKER_BUILDKIT: "1"
      - name: Test
        run: |
          ./run lint
          ./run test
          shellcheck ./run
